---
PLAINTEXT_VARIABLES:
    ENVIRONMENT: devel
    AWS_REGION: us-east-1
    LOG_LEVEL: info
    DO_NOT_UPDATE: True
    REDSHIFT_DB_NAME: qa
    REDSHIFT_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKIwgZ8GCSqGSIb3DQEHBqCBkTCBjgIBADCBiAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzfC7it2NYa1YnFy+4CARCAW1NrqGfSfPptEF4epEXl8Hr6ntrJcZ0DE1GeGt2c2mMnMt7hcim39NTgxHvi5DIldF4J2UJzgG0KBs5UGRU9dyjrQu5zLfdB8Kv50d1lHfvqM2aDQAK0SQ188BY=
    REDSHIFT_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHkwdwYJKoZIhvcNAQcGoGowaAIBADBjBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMwWbsfMujNlSJkI0gIBEIA2fK9zhCIH2IzQoPEyQ138iFELRIpDrQkvXzgsQZYFAuavxgKW4pKjnld1kgZbhOx+OB6euBd2
    REDSHIFT_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPRmwXfref9Y8uIvgQIBEIAvN65O4c0svI9bz0HoaUCjmuwbh2mcPVCX0BnRSJUf0uRz6idqI2yarZzrahtHWM8=
...